-- MySQL Script generated by MySQL Workbench
-- 10/27/15 10:35:03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema Bank
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Bank
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Bank` DEFAULT CHARACTER SET utf8 ;
USE `Bank` ;

-- -----------------------------------------------------
-- Table `Bank`.`Rekeningtype`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Bank`.`Rekeningtype` ;

CREATE TABLE IF NOT EXISTS `Bank`.`Rekeningtype` (
  `Rekeningtype_ID` INT NOT NULL AUTO_INCREMENT,
  `Rekeningsbeschrijving` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Rekeningtype_ID`),
  UNIQUE INDEX `Rekeningtype_ID_UNIQUE` (`Rekeningtype_ID` ASC),
  UNIQUE INDEX `Rekeningsbeschrijving_UNIQUE` (`Rekeningsbeschrijving` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Bank`.`Rekeningshouder`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Bank`.`Rekeningshouder` ;

CREATE TABLE IF NOT EXISTS `Bank`.`Rekeningshouder` (
  `Rekeningshouder_ID` INT NOT NULL AUTO_INCREMENT,
  `Voornaam` VARCHAR(45) NOT NULL,
  `Achternaam` VARCHAR(45) NOT NULL,
  `Geboortedatum` VARCHAR(45) NOT NULL,
  `Woonplaats` VARCHAR(45) NOT NULL,
  `Postcode` VARCHAR(6) NOT NULL,
  `Huisnummer` INT(11) NOT NULL,
  `Telefoonnummer` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`Rekeningshouder_ID`),
  UNIQUE INDEX `Rekeningshouder_ID_UNIQUE` (`Rekeningshouder_ID` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Bank`.`Rekening`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Bank`.`Rekening` ;

CREATE TABLE IF NOT EXISTS `Bank`.`Rekening` (
  `Rekening_ID` INT NOT NULL AUTO_INCREMENT,
  `Saldo` DOUBLE NOT NULL,
  `Limiet` DOUBLE NOT NULL,
  `Rekeningtype_Rekeningtype_ID` INT NOT NULL,
  `Rekeningshouder_Rekeningshouder_ID` INT NOT NULL,
  `Pincode` INT(11) NOT NULL,
  PRIMARY KEY (`Rekening_ID`),
  UNIQUE INDEX `Rekening_ID_UNIQUE` (`Rekening_ID` ASC),
  INDEX `fk_Rekening_Rekeningtype1_idx` (`Rekeningtype_Rekeningtype_ID` ASC),
  INDEX `fk_Rekening_Rekeningshouder1_idx` (`Rekeningshouder_Rekeningshouder_ID` ASC),
  CONSTRAINT `fk_Rekening_Rekeningtype1`
    FOREIGN KEY (`Rekeningtype_Rekeningtype_ID`)
    REFERENCES `Bank`.`Rekeningtype` (`Rekeningtype_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Rekening_Rekeningshouder1`
    FOREIGN KEY (`Rekeningshouder_Rekeningshouder_ID`)
    REFERENCES `Bank`.`Rekeningshouder` (`Rekeningshouder_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Bank`.`Afschrijvingen`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Bank`.`Afschrijvingen` ;

CREATE TABLE IF NOT EXISTS `Bank`.`Afschrijvingen` (
  `Afschrift_ID` INT NOT NULL AUTO_INCREMENT,
  `Datum` DATETIME NOT NULL,
  `Geslaagd` TINYINT(1) NOT NULL,
  `Rekening_Rekening_ID` INT NOT NULL,
  `Bedrag` DOUBLE NOT NULL,
  PRIMARY KEY (`Afschrift_ID`),
  UNIQUE INDEX `Afschrift_ID_UNIQUE` (`Afschrift_ID` ASC),
  INDEX `fk_Afschrijvingen_Rekening_idx` (`Rekening_Rekening_ID` ASC),
  CONSTRAINT `fk_Afschrijvingen_Rekening`
    FOREIGN KEY (`Rekening_Rekening_ID`)
    REFERENCES `Bank`.`Rekening` (`Rekening_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
